apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-db-deployment
  namespace: application
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      db: hospital
  template:
    metadata:
      labels:
        app: postgres
        db: hospital
    spec:
      containers:
        - name: hospital-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: hospital-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hospital-data
      restartPolicy: Always
      volumes:
        - name: hospital-data
          persistentVolumeClaim:
            claimName: hospital-db-volume-claim
      