apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application
  name: hospital-db-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: "hospitaldatabase"
  POSTGRES_USER: "hospitaluser"
  POSTGRES_PASSWORD: "hospitalpassword"
  