apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice-deployment
  namespace: application
  labels:
    chatservice: chatservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      chatservice: chatservice
  template:
    metadata:
      name: chat-service
      labels:
        chatservice: chatservice
    spec:
      containers:
        - name: chatservice
          image: ghcr.io/defau1t17/chatservice:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: chat-service-configmap
          imagePullPolicy: Always
      restartPolicy: Always

