services:
  chat_db:
    container_name: chat
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=authentication'
      - 'POSTGRES_PASSWORD=authentication'
      - 'POSTGRES_USER=authentication'
    ports:
      - 5448:5432
    restart: always

  hostpital_db:
    container_name: hospital
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=hospital'
      - 'POSTGRES_PASSWORD=hospital'
      - 'POSTGRES_USER=hospital'
    ports:
      - 5411:5432
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis:latest
    container_name: caching
    ports:
      - 6379:6379
