FROM maven:3-openjdk-17-slim AS BUILD

WORKDIR /hostpitalService
COPY HospitalService/ .

RUN mvn clean package

#-------------------------------
FROM openjdk:17 AS DEPLOY

ENV serviceName="hospital.jar"
WORKDIR /deployment
COPY --from=BUILD /hostpitalService/target/HospitalService-SNAPSHOT.jar $serviceName
EXPOSE 8086

ENTRYPOINT java -jar $serviceName
