services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=telegramusers'
      - 'POSTGRES_PASSWORD=telegrambot'
      - 'POSTGRES_USER=telegrambot'
    ports:
      - 5432:5432
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
