pipeline {
    agent any
    environment {
        BUILD_VOLUME = "${env.JOB_NAME}-${env.BUILD_NUMBER}"
    }
    stages{
        stage("config variable") {
            steps {
                script {
                    sh "docker volume create --name=${BUILD_VOLUME}"
                }
            }
        }
        stage("test"){
            steps{
                withDockerContainer(args: "-v ${BUILD_VOLUME}:/var/jenkins_home/workspace/${env.JOB_NAME}" ,image: 'alpine') {
                    sh 'apk update && apk add git docker'
                    sh 'git clone -b develop https://github.com/defau1t17/PatientDoctorTelegramBot; cd PatientDoctorTelegramBot/; docker build -t hospitalservice:latest  --file Dockerfile.hospitalservice .'
                }
            }    
            post{
                always {
                    sh "docker volume rm ${BUILD_VOLUME}"
                }
            }
        }
    }
}

