apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: main
    - port: 15672
      name: secondname
  type: ClusterIP
  