apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: '{{.Values.doctorbot.service_name }}'
spec:
  selector:
    app: doctor-bot
  ports:
    - port: {{.Values.doctorbot.port}}
  type: ClusterIP
  