apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: '{{.Values.redis.service_name }}'
spec:
  selector:
    app: redis
  ports:
    - port: {{.Values.redis.container_port }}
  type: ClusterIP
