FROM maven:3-openjdk-17-slim AS BUILD

WORKDIR /doctorbot
COPY ../DoctorTelegramBot .

RUN mvn clean  package

#-------------------------------
FROM openjdk:17 AS DEPLOY

ENV serviceName="doctorbot.jar"
WORKDIR /deployment
COPY --from=BUILD /doctorbot/target/DoctorTelegramBot-SNAPSHOT.jar $serviceName
EXPOSE 8088

ENTRYPOINT java -jar $serviceName
