FROM maven:3-openjdk-17-slim AS BUILD

WORKDIR /emergencyService
COPY ../EmergencyService .

RUN mvn clean package

#-------------------------------
FROM openjdk:17 AS DEPLOY

ENV serviceName="emergency.jar"
WORKDIR /deployment
COPY --from=BUILD /emergencyService/target/EmergencyService-SNAPSHOT.jar $serviceName
EXPOSE 8084

ENTRYPOINT java -jar $serviceName
