apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
  namespace: application
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: '{{ .Values.rabbit_config.container_name }}'
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.rabbit_config.main_port }}
            - containerPort: {{ .Values.rabbit_config.second_port }}
          envFrom:
            - configMapRef:
                name: rabbitmq-config-map
      restartPolicy: Always
      