apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config-map
  namespace: application
  labels:
    app: rabbitmq
data:
  RABBITMQ_DEFAULT_PASS: '{{ .Values.rabbit_config.username }}'
  RABBITMQ_DEFAULT_USER: '{{ .Values.rabbit_config.password }}'
