apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: '{{.Values.rabbit_config.service_name }}'
spec:
  selector:
    app: rabbitmq
  ports:
    - port: {{ .Values.rabbit_config.main_port }}
      name: main
    - port: {{ .Values.rabbit_config.second_port }}
      name: secondname
  type: ClusterIP
  