apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-telegram-bot-deployment
  namespace: application
  labels:
    app: patient-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-bot
  template:
    metadata:
      name: patient-bot
      labels:
        app: patient-bot
    spec:
      containers:
        - name: patient-bot
          image: ghcr.io/defau1t17/patientbot:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: patient-telegram-bot-config-map
          imagePullPolicy: Always
      restartPolicy: Always
      