apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-telegram-bot-config-map
  namespace: application
  labels:
    app: patient-bot
data:
  PATIENT_TOKEN: "token"
  HOSPITAL_SERVICE_ADDRESS: "hospitalservice"
  CHAT_SERVICE_ADDRESS: "chatservice"
  EMERGENCY_SERVICE_ADDRESS: "emergencyservice"
  