apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emergency-service
spec:
  destination:
    name: ''
    namespace: application
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/applications/emergency-service
    repoURL: 'https://github.com/defau1t17/PatientDoctorTelegramBot'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
