apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emergency-service
spec:
  destination:
    name: ''
    namespace: application
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://defau1t17.github.io/PatientDoctorTelegramBot/'
    targetRevision: 1.0.0
    chart: emergency-service
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
