apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-telegram-bot-config-map
  namespace: application
  labels:
    app: doctor-bot
data:
  DOCTOR_TOKEN: "token"
  RABBITMQ_PASS: "guest"
  RABBITMQ_USER: "guest"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  CHAT_SERVICE_ADDRESS: "chatservice"
  HOSPITAL_SERVICE_ADDRESS: "hospitalservice"
