apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: application
  name: hospital-db-volume
  labels:
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  hostPath:
    path: /mnt/hospital