apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: '{{.Values.service.name }}'
spec:
  selector:
    db: hospital
  ports:
    - port: {{ .Values.service.port }}
  type: ClusterIP
  