apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application
  name: hospital-db-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: '{{.Values.database.name }}'
  POSTGRES_USER: '{{.Values.database.username}}'
  POSTGRES_PASSWORD: '{{.Values.database.password}}'
  