apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: {{ .Values.service.service_name }}
spec:
  selector:
    chatservice: chatservice
  ports:
    - port: {{ .Values.service.chat_service_port }}
  type: LoadBalancer
  