apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      jenkins: jenkins-server
  template:
    metadata:
      labels:
        jenkins: jenkins-server
    spec:
      containers:
        - name: '{{.Values.jenkins.container_name}}'
          image: ghcr.io/defau1t17/jenkins-server:latest
          ports:
            - containerPort: {{.Values.jenkins.port}}
