apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      jenkins: jenkins-container
  template:
    metadata:
      labels:
        jenkins: jenkins-container
    spec:
      containers:
      - name: jenkins
        image: ghcr.io/defau1t17/jenkins-server:latest
        ports:
        - containerPort: 8080
