apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application
  name: emergency-service-configmap
  labels:
    app: emergency-service
data:
  RABBITMQ_DEFAULT_PASS: "guest"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  HOSPITAL_SERVICE_ADDRESS: "hospitalservice"


  