apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-db-secret
  namespace: application
  labels:
    app: postgres
data:
  POSTGRES_DB: '{{.Values.database.name}}'
  POSTGRES_USER: '{{.Values.database.username}}'
  POSTGRES_PASSWORD: '{{.Values.database.password}}'
  