apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: application
  name: chat-db-volume-claim
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: chat-db-volume
  storageClassName: fast
